Merge pull request #426 in SPKR/keel-nflx from use-cheaper-timer to master
Squashed commit of the following:

commit 4cd7e1669e961643d4c506a0c3e61b3a3b9dd6a0
Author: Lorin Hochstein <lhochstein@netflix.com>
Date:   Thu Jul 15 20:15:52 2021 -0700

    fix(metrics): don't use percentile timer

    Problem:

    We hit a transient issue that involved a huge spike in Java object
    allocation, long GC pauses, and a Java out-of-memory (OOM) error.

    The stack trace involved the spectator PercentileTimer in the
    LifecycleMonitorSchedule:

        java.lang.OutOfMemoryError: Java heap space
          at com.netflix.spectator.api.ArrayTagSet.addAll(ArrayTagSet.java:144)
          at com.netflix.spectator.api.DefaultId.withTags(DefaultId.java:68)
          at com.netflix.spectator.api.DefaultId.withTags(DefaultId.java:27)
          at com.netflix.spectator.api.histogram.PercentileTimer$Builder.build(PercentileTimer.java:180)
          at com.netflix.spinnaker.keel.lifecycle.LifecycleMonitorScheduler.recordDuration(LifecycleMonitorScheduler.kt:118)
          at com.netflix.spinnaker.keel.lifecycle.LifecycleMonitorScheduler.invokeMonitoring(LifecycleMonitorScheduler.kt:111)

    Solution:

    We don't know for certain that the OOM trigger here is related to the underlying problem. However, percentile timers are known to have [poor worst-case performance][1].

    To be on the safe side, this PR switches from using a PercentileTimer to a regular timer.
    THe downside is that we won't be able to look at percentiles, only min/avg/max.

    [1]: https://www.javadoc.io/doc/com.netflix.spectator/spectator-api/latest/com/netflix/spectator/api/histogram/PercentileTimer.html

(cherry picked from commit 7494b204bc29c599325300def7bac3e305c76aec)